# Generated by Django 4.1 on 2022-09-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageadmin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagemodel",
            old_name="Image",
            new_name="image",
        ),
    ]
